---
title: "Simulation testing of state space models in R and JD+"
author: "Duncan Elliott"
date: "12 March 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary

# What's been done

# Simulation

```{r simulate}
library(KFAS)
library(rjdssf)

jd_bsm<-function(x, nar=0){
  # create the model
  bsm<-jd3_ssf_model()
  # create the components and add them to the model
  ssf.add(bsm, jd3_ssf_locallineartrend("ll"))
  ssf.add(bsm, jd3_ssf_seasonal("s", 12, type="Dummy"))
  if (nar == 1){
    ssf.add(bsm, jd3_ssf_sae("n", .5, lag=3))
  }else if (nar == 2){
    ssf.add(bsm, jd3_ssf_sae("n", c(.3, .2), lag=3))
  }
  # create the equation 
  if (nar == 0){
    eq<-jd3_ssf_equation("eq", .01, F)
  }else{
    eq<-jd3_ssf_equation("eq")
  }
  ssf.add(eq, "ll")
  ssf.add(eq, "s")
  if (nar >0){
    ssf.add(eq, "n")
  }
  ssf.add(bsm, eq)
  #estimate the model
  rslt<-ssf.estimate(bsm, x, precision=1e-9)
}

kfas_bsm <- function(x,init_val,optim_method="BFGS"){
  mdl <- SSModel(x ~ -1+SSMtrend(2, Q = list(NA,NA))+
   SSMseasonal(period = 12, sea.type="dummy", Q = NA), H = NA)
  est_mdl <- fitSSM(mdl, rep(init_val,4),
                  method = optim_method)
  mdl <- est_mdl$model
  out <- KFS(mdl, filtering = c("state","disturbance"), smoothing = c("state","disturbance"))
  rslt <- list(hyper_est=est_mdl,out=out)
  return(rslt)
}

set.seed(20)

y <- rep(NA,120)
  
var_level <- 0.1
var_slope <- 0.3
var_seas <- 0.5
var_noise <- 0.7
  mdl_raw <- SSModel(y ~ -1+SSMtrend(2, Q = list(var_level,var_slope))+
   SSMseasonal(period = 12, sea.type="dummy", Q = var_seas), H = var_noise)
init_val <- 0
sim <-  simulateSSM(mdl_raw,type="observations")

ts.plot(sim)

bsm_simul<-NULL
n <- 200
sim_start <- Sys.time()
jd_estimate <- NULL
kfas_estimate <- NULL
for(i in 1:n){
   sim <-  simulateSSM(mdl_raw,type="observations")[,1,1]
   bsm_simul<-cbind(bsm_simul, matrix(sim, 120, 1))
   jd_start <- Sys.time()
   q <- jd_bsm(sim,nar=0)
   jd_end <- Sys.time()
   jd_dur <- jd_end-jd_start
   s <- result(q, "scalingfactor") 
   p<-result(q, "parameters")
   jd_estimate <- rbind(jd_estimate,as.numeric(c(jd_dur,-1*result(q,"loglikelihood"),s*p[c(1:3)],s*p[length(p)]*p[length(p)])))
   kfas_start <- Sys.time()
   r <- kfas_bsm(sim,init_val)
   kfas_end <- Sys.time()
   kfas_dur <- kfas_end-kfas_start
   kfas_estimate <- rbind(kfas_estimate, c(kfas_dur,r$hyper_est$optim.out$value,diag(r$out$model$Q[,,1]),r$out$model$H[,,1]))
}
sim_end <- Sys.time()
sim_dur <- sim_end-sim_start

print(paste("Number of simulations =",n))
print(paste("JD+ average execution time =",sum(jd_estimate[2:n,1])/(n-1)))
print(paste("KFAS average execution time =",sum(kfas_estimate[2:n,1])/(n-1)))
print("JD+ likelihood - KFAS likelihood")
print(summary(kfas_estimate[,2]-jd_estimate[,2]))


est_nams <- c("Run time per series","Negative Loglikelihood","Level Variance","Slope Variance","Seasonal Variance","Observation variance")
for(i in 1:ncol(jd_estimate)){
  boxplot(data.frame(JD=jd_estimate[,i],KFAS=kfas_estimate[,i]),main=est_nams[i])
  if(i==3){abline(h=var_level,lty=2,col=2)}
  if(i==4){abline(h=var_slope,lty=2,col=2)}
  if(i==5){abline(h=var_seas,lty=2,col=2)}
  if(i==6){abline(h=var_noise,lty=2,col=2)}
}

```
# Simulation of sampling error autocorrelation variances only
Ie assume the correlation is known
```{r simulate_sae}
  rho.1 <- 0     # value of wave1  AR coefficient
  rho.2 <- 0.8                       # value of wave 2  AR coefficient
  rho.3 <- 0.7                       # value of wave 3 AR coefficient
  rho.4 <- 0.6                       # value of wave 4 AR coefficient
  rho.5 <- 0.8                       # value of second AR coefficient
  var1 <- 1
  var2 <- 2
  var3 <- 3
  var4 <- 4
  var5 <- 5

  data.len<-60    
    
  obs.matrix.err <- cbind(diag(1,5),matrix(0,nrow=5,ncol=8))

  trans.matrix.err <- rbind(matrix(0,1,13),
          cbind(matrix(0,4,9),diag(c(rho.2,rho.3,rho.4,rho.5))),
          cbind(diag(4),matrix(0,4,9)),
          cbind(matrix(0,4,5),diag(4),matrix(0,4,4))
    )
Z_mat <- obs.matrix.err
T_mat <- trans.matrix.err
H_mat <- diag(0,5)*1
R_mat <- matrix(0,13,5)
R_mat[1,1] <- 1  #error w1 variance
R_mat[2,2] <- sqrt(1-rho.2^2)  #error w2 variance
R_mat[3,3] <- sqrt(1-rho.3^2)  #error w3 variance
R_mat[4,4] <- sqrt(1-rho.4^2)  #error w4 variance
R_mat[5,5] <- sqrt(1-rho.5^2)  #error w5 variance 

Q_mat <- diag(c(var1,var2,var3,var4,var5))

se <- matrix(NA,data.len,5)

mdl_raw2 <- SSModel(se ~ -1+SSMcustom(Z_mat, T_mat, R_mat, Q = Q_mat,P1=diag(13)), H = H_mat)
sim <-  simulateSSM(mdl_raw2,type="observations")[,,1]

acf(sim)


v_tv <- matrix(1,1,5)

jd_sae_only<-function(x, ar=c(rho.2,rho.3,rho.4,rho.5),v=v_tv){
  # create the model
  ons<-jd3_ssf_model()
  
  # multivariate survey errors 
  # 5 waves, ar(1) models, given r2...r5 (fixed here to .22... 25), lag = 3
  add(ons, jd3_ssf_msae3("sae",array(0.01, 5), F, ar=ar, fixedar = T, v, lag=3))
  
  # survey errors (set to 1.x for wave x + some noise)
  
  # create the equations 
  eq1<-jd3_ssf_equation("eq1", 0, T)
  ssf.add(eq1, "sae", loading=jd3_ssf_loading(0))
  ssf.add(ons,eq1)
  eq2<-jd3_ssf_equation("eq2", 0, T)
  ssf.add(eq2, "sae", loading=jd3_ssf_loading(1))
  ssf.add(ons,eq2)
  eq3<-jd3_ssf_equation("eq3", 0, T)
  ssf.add(eq3, "sae", loading=jd3_ssf_loading(2))
  ssf.add(ons, eq3)
  eq4<-jd3_ssf_equation("eq4", 0, T)
  ssf.add(eq4, "sae", loading=jd3_ssf_loading(3))
  ssf.add(ons, eq4)
  eq5<-jd3_ssf_equation("eq5", 0, T)
  ssf.add(eq5, "sae", loading=jd3_ssf_loading(4))
  ssf.add(ons, eq5)
  return (ssf.estimate(ons, x, precision=1e-9))
}

   
kfas_sae <- function(x,init_val,optim_method="BFGS"){
  obs.matrix.err <- cbind(diag(1,5),matrix(0,nrow=5,ncol=8))

  trans.matrix.err <- rbind(matrix(0,1,13),
          cbind(matrix(0,4,9),diag(c(rho.2,rho.3,rho.4,rho.5))),
          cbind(diag(4),matrix(0,4,9)),
          cbind(matrix(0,4,5),diag(4),matrix(0,4,4))
    )
   Z_mat <- obs.matrix.err
   T_mat <- trans.matrix.err
   H_mat <- diag(0,5)*1
   R_mat <- matrix(0,13,5)
   R_mat[1,1] <- 1  #error w1 variance
   R_mat[2,2] <- sqrt(1-rho.2^2)  #error w2 variance
   R_mat[3,3] <- sqrt(1-rho.3^2)  #error w3 variance
   R_mat[4,4] <- sqrt(1-rho.4^2)  #error w4 variance
   R_mat[5,5] <- sqrt(1-rho.5^2)  #error w5 variance 

   Q_mat <- diag(c(NA,NA,NA,NA,NA))

   mdl <- SSModel(x ~ -1+SSMcustom(Z_mat, T_mat, R_mat, Q = Q_mat,P1=diag(13)), H = H_mat)
   est_mdl <- fitSSM(mdl, rep(init_val,5),
                  method = optim_method)
   mdl <- est_mdl$model
   out <- KFS(mdl, filtering = c("state","disturbance"), smoothing = c("state","disturbance"))
   rslt <- list(hyper_est=est_mdl,out=out)
   return(rslt)
}




n <- 200
sim_start <- Sys.time()
jd_estimate <- NULL
kfas_estimate <- NULL
for(i in 1:n){
   sim <-  simulateSSM(mdl_raw2,type="observations")[,,1]
   jd_start <- Sys.time()
   q <- jd_sae_only(sim)
   jd_end <- Sys.time()
   jd_dur <- jd_end-jd_start
   s <- result(q, "scalingfactor") 
   p<-result(q, "parameters")
   jd_estimate <- rbind(jd_estimate,as.numeric(c(jd_dur,-1*result(q,"loglikelihood"),s*p[c(1:5)])))
   kfas_start <- Sys.time()
   r <- kfas_sae(sim,init_val)
   kfas_end <- Sys.time()
   kfas_dur <- kfas_end-kfas_start
   kfas_estimate <- rbind(kfas_estimate, c(kfas_dur,r$hyper_est$optim.out$value,diag(r$out$model$Q[,,1])))
}
sim_end <- Sys.time()
sim_dur <- sim_end-sim_start

print(paste("Number of simulations =",n))
print(paste("JD+ average execution time =",sum(jd_estimate[2:n,1])/(n-1)))
print(paste("KFAS average execution time =",sum(kfas_estimate[2:n,1])/(n-1)))
print("JD+ likelihood - KFAS likelihood")
print(summary(kfas_estimate[,2]-jd_estimate[,2]))


est_nams <- c("Run time per series","Negative Loglikelihood","W1 Variance","W2 Variance","W3  Variance","W4 Variance","W5 Variance")
for(i in 1:ncol(jd_estimate)){
  boxplot(data.frame(JD=jd_estimate[,i],KFAS=kfas_estimate[,i]),main=est_nams[i])
  if(i==3){abline(h=var1,lty=2,col=2)}
  if(i==4){abline(h=var2,lty=2,col=2)}
  if(i==5){abline(h=var3,lty=2,col=2)}
  if(i==6){abline(h=var4,lty=2,col=2)}
  if(i==7){abline(h=var5,lty=2,col=2)}
}


```


# Simulation of SAE with bias 
```{r simulate_sae_bias}
print("Not done yet")
```

# Simulation of full model 
```{r simulate_full}
print("Not done yet")
```
# Actual series
```{r}
load("../Data/retail.rda")
n<-length(retail)
jd_estimate <- NULL
kfas_estimate <- NULL
for(i in 1:n){
  y<-log(retail[[i]])
   jd_start <- Sys.time()
   q <- jd_bsm(y,nar=0)
   jd_end <- Sys.time()
   jd_dur <- jd_end-jd_start
   s <- result(q, "scalingfactor") 
   p<-result(q, "parameters")
   jd_estimate <- rbind(jd_estimate,as.numeric(c(jd_dur,result(q,"loglikelihood"),s*p[c(1:3)],s*p[length(p)]*p[length(p)])))
   kfas_start <- Sys.time()
   r <- kfas_bsm(y,init_val)
   kfas_end <- Sys.time()
   kfas_dur <- kfas_end-kfas_start
   kfas_estimate <- rbind(kfas_estimate, c(kfas_dur,-r$hyper_est$optim.out$value,diag(r$out$model$Q[,,1]),r$out$model$H[,,1]))
}
sim_end <- Sys.time()
sim_dur <- sim_end-sim_start

print(paste("Number of simulations =",n))
print(paste("JD+ average execution time =",sum(jd_estimate[1:n,1])/(n-1)))
print(paste("KFAS average execution time =",sum(kfas_estimate[1:n,1])/(n-1)))
print("JD+ likelihood - KFAS likelihood")
del<-jd_estimate[,2]-kfas_estimate[,2]
print(summary(del))
plot(del)

```
